# Generated by Django 5.0.6 on 2024-06-28 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='created_by',
        ),
    ]
