# Generated by Django 5.0.6 on 2024-09-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_services_options_reserve_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
