# Generated by Django 5.0.6 on 2024-12-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_date_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
